version: '3.9'

services:

  redis:
    image: redis
    restart: always
  
  webapp:
    container_name: django
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["python3", "./referal/manage.py","runserver", "0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./cc:/referal/
    command: ['celery', '--workdir=./referal', '-A', 'referal', 'worker']
#  db:
#    container_name: pg_db
#    image: postgres:13.3
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#      POSTGRES_DB: db
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#
#
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
